<a href="https://colab.research.google.com/github/ricardoricrob76/machinelearning/blob/main/DEEP-PyTorch_Lesson_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensor  is the central part of the package. If you set its attribute .requires_grad as True, it starts to track all operations on it. When you finish your computation you can call .backward() and have all the gradients computed automatically. The gradient for this tensor will be accumulated into .grad attribute. To stop a tensor from tracking history, you can call .detach()

![Gradient Descent Image](https://miro.medium.com/max/875/1*7lt0nKyzIYzAJf1luO0jxw.jpeg)


https://medium.com/quantyca/gradient-descent-in-deep-learning-b1077b89af81

[Gradient Descent Simulator](https://lukaszkujawa.github.io/gradient-descent.html)

In [ ]:
import torch
#Create a tensor and set requires_grad=True to track computation with it

x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [ ]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [ ]:
print(y.grad_fn)

In [ ]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [ ]:
print(out)

tensor(27., grad_fn=<MeanBackward0>)


In [ ]:
a = torch.randn(2, 2)
print(a)


tensor([[-0.1908,  0.2920],
        [ 0.1323, -1.1934]])


In [ ]:
a = ((a * 3) / (a - 1))
print(a.requires_grad)

False


In [ ]:
print(a)

tensor([[ 0.4807, -1.2372],
        [-0.4576,  1.6323]])


In [ ]:
a.requires_grad_(True)
print(a.requires_grad)


True


In [ ]:
b = (a * a).sum()
print(b.grad_fn)

In [ ]:
print(b)

tensor(4.6353, grad_fn=<SumBackward0>)


In [ ]:
print(out)

tensor(27., grad_fn=<MeanBackward0>)


In [ ]:
out.backward()

Let’s backprop now. Because out contains a single scalar, out.backward() is equivalent to out.backward(torch.tensor(1.)).

In [ ]:
print(out)

tensor(27., grad_fn=<MeanBackward0>)


In [ ]:
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [ ]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
