<a href="https://colab.research.google.com/github/ricardoricrob76/machinelearning/blob/main/DEEP-PytORCH_Class1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from __future__ import print_function
import torch

## Create a empy tensor

In [ ]:
x = torch.empty(5, 3)
print(x)

tensor([[1.2670e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 6.4460e-44],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 4.7343e-36]])


**Construct a randomly initialized matrix:**

In [ ]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3688, 0.4395, 0.2899],
        [0.9599, 0.6814, 0.7465],
        [0.0984, 0.4816, 0.9918],
        [0.7163, 0.4031, 0.1137],
        [0.6782, 0.2800, 0.2421]])


**Construct a matrix filled zeros and of dtype long:**

In [ ]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


**Construct a tensor for data**

In [ ]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [ ]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)  

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.2248,  0.4996,  0.8468],
        [ 0.0096,  2.0772, -1.4811],
        [-1.0125, -0.1888, -1.0171],
        [ 0.3507,  2.0612,  1.9400],
        [ 1.1977, -0.1413,  0.8477]])


**Get the size**

In [ ]:
print(x.size())

torch.Size([5, 3])


**Add to torch tensors**

In [ ]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.9492,  1.1706,  1.2335],
        [ 0.0275,  2.8898, -1.4213],
        [-0.6250,  0.4644, -0.0658],
        [ 0.6659,  2.7903,  2.6239],
        [ 1.3990,  0.2948,  1.7792]])


In [ ]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.9492,  1.1706,  1.2335],
        [ 0.0275,  2.8898, -1.4213],
        [-0.6250,  0.4644, -0.0658],
        [ 0.6659,  2.7903,  2.6239],
        [ 1.3990,  0.2948,  1.7792]])
