<a href="https://colab.research.google.com/github/ricardoricrob76/machinelearning/blob/main/DEEP-PyTorchLesson2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [ ]:
print(z)

tensor([[-0.2379,  0.0264, -0.7292,  1.2250,  1.1846,  0.7632, -0.0530, -0.2612],
        [ 0.8651,  0.9234,  0.3384, -0.1644, -0.1896,  1.2391,  0.1103,  0.5077]])


In [ ]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.2743])
0.27429237961769104


Converting to numpy array

In [ ]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [ ]:
a.add_(1)
print(a)
print(b)


tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Convert numpy to Cuda

In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
# We will use ``torch.device`` objects to move tensors in and out of GPU

device = torch.device("cpu")          # a CUDA device object
y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
x = x.to(device)                       # or just use strings ``.to("cuda")``
z = x + y
print(z)
print(z.to("cpu", torch.double))  

tensor([1.2743])
tensor([1.2743], dtype=torch.float64)
