<a href="https://colab.research.google.com/github/ricardoricrob76/machinelearning/blob/main/ENAP_Case1_01_Implementa%C3%A7%C3%A3o_do_Modelo_Algoritmo_%3E_Naive_Bayes_Analise_de_Credito_Bancario_Open_Banking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Gerando Modelo de Machine Learning (Classificação) com Algoritmo Naive Bayes
# Composição de Vendas Compras Centralizadas no Governo Federal
# Mês de Referência: Novembro / 2021.

In [ ]:
# Autor: Ricardo Roberto de Lima
# -*- coding: utf-8 -*-

In [ ]:
#Conjunto de importacoes
import numpy as np
import pandas as pd
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [ ]:
#Carrega o dataset com os dados para o treinamento e validacao
dados_compras_treino = pd.read_csv("dados_limitecredito.csv", encoding="utf-8")

In [ ]:
#Definição dos atributos que deverao ser treinados para gerar o modelo de classificacao
data_treino = np.array(dados_compras_treino[['historico_credito','divida', 'garantias', 'renda']])
#Definição do atributo de classificacao
data_classif = np.array(dados_compras_treino['Risco'])

In [ ]:
#Definição dos conjuntos de treinamento e validação
x_treino, x_val, y_treino, y_val = train_test_split(data_treino, data_classif, test_size=0.25)

In [ ]:
#Apresentacao dos dados selecionados para o conjunto de treinamento e validacao
print("-----------------------")
print("Conjunto de Treinamento")
print(x_treino)
print("Conjunto de Validacao")
print(x_val)
print("-----------------------")

-----------------------
Conjunto de Treinamento
[[    1     2     1 23780]
 [    2     1     1 38900]
 [    3     2     1 20000]
 [    3     2     1  9000]
 [    2     1     2 40000]
 [    2     1     1 29000]
 [    2     2     1 28000]
 [    3     2     1 56709]
 [    1     1     1 12000]
 [    3     2     2 45600]]
Conjunto de Validacao
[[    1     1     2 43222]
 [    2     1     1 40000]
 [    1     2     1 10000]
 [    3     1     1 56000]]
-----------------------


In [ ]:
#Treinamento do modelo com os dados atribuidos ao conjunto de treinamento
modelo_NB = GaussianNB()
modelo_NB.fit(x_treino, y_treino)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
#Predição e acurácia para o conjunto de treinamento
print("Predicao para o conjunto de treinamento")
y_pred_treino = modelo_NB.predict(x_treino)
print("Acuracia para o conjunto de treinamento")
print(accuracy_score(y_treino, y_pred_treino))
print("-----------------------")

Predicao para o conjunto de treinamento
Acuracia para o conjunto de treinamento
0.9
-----------------------


In [ ]:
#Predição e acurácia para o conjunto de validação
print("Predicao para o conjunto de validacao")
y_pred_val = modelo_NB.predict(x_val)
print("Acuracia para o conjunto de validacao")
print(accuracy_score(y_val, y_pred_val))
print("-----------------------")

Predicao para o conjunto de validacao
Acuracia para o conjunto de validacao
0.5
-----------------------


In [ ]:
# Persistência do Modelo de Machine Learning
# Autor: Ricardo Roberto de Lima